#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import argparse
import for_lossless_music as flm

parser = argparse.ArgumentParser(
    prog='for-lossless-music',
    usage='for-lossless-music [OPTION]...keyword...',
    description='For lossless music!',
)

parser.add_argument(
    '-V', '--version', action='store_true',
    help='Print version'
)

parser.add_argument(
    '-s', '--source', metavar='source', default=None,
    help='Which source you want to search. now support: qq(QQ), kw(酷我), default source is qq'
)

parser.add_argument(
    '-p', '--page', metavar='page', type=int, default=1,
    help='What page do you what to display, default is 1'
)

parser.add_argument(
    '-n', '--num', metavar='num', type=int, default=20,
    help='How many rows are display on a page'
)

parser.add_argument('keyword', nargs='+', help=argparse.SUPPRESS)

args = parser.parse_args()

if args.version:
    print(flm.__version__)

if len(args.keyword) > 1:
    print("Too many keywords")
    sys.exit()

total, songs = flm.Moresound.search(args.keyword[0], args.source, args.page, args.num)
table = flm.songs2table(songs)
print('total', total)
print(table)
